### ISSUE TITLE
Error running module

### ISSUE THREAD

**Issue by mohammada315** [SamuelDudley/MAVCesium#46]
Hello
I get an error when I run the module
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mohammad/.local/lib/python3.8/site-packages/MAVProxy-1.8.39-py3.8.egg/MAVProxy/modules/mavproxy_cesium/app/cesium_web_server.py", line 141, in main
  File "/home/mohammad/.local/lib/python3.8/site-packages/MAVProxy-1.8.39-py3.8.egg/MAVProxy/modules/mavproxy_cesium/app/cesium_web_server.py", line 104, in start_app
  File "/home/mohammad/.local/lib/python3.8/site-packages/tornado-6.2.dev1-py3.8-linux-x86_64.egg/tornado/tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "/home/mohammad/.local/lib/python3.8/site-packages/tornado-6.2.dev1-py3.8-linux-x86_64.egg/tornado/tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "/home/mohammad/.local/lib/python3.8/site-packages/tornado-6.2.dev1-py3.8-linux-x86_64.egg/tornado/netutil.py", line 246, in add_accept_handler
    io_loop = IOLoop.current()
  File "/home/mohammad/.local/lib/python3.8/site-packages/tornado-6.2.dev1-py3.8-linux-x86_64.egg/tornado/ioloop.py", line 264, in current
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.



```

**Comment by Ryanf55** [comment]
Fixed in ArduPilot's fork: https://github.com/ArduPilot/MAVCesium

Specifically, 
https://github.com/ArduPilot/MAVCesium/pull/4

This is caused by newer Tornado versions 5 and 6 changing how they interract with the main thread with the introduction and standardization of asyncio.
